fix: output cjs
ReferenceError: module is not defined in ES module scope This file is being treated as an ES module because it has a '.js' file extension and '/code/node_modules/progressive-chatgpt-bot/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension. at file:///code/node_modules/progressive-chatgpt-bot/dist/index.js:3555:1 at ModuleJob.run (node:internal/modules/esm/module_job:198:25) at async Promise.all (index 0) at async ESMLoader.import (node:internal/modules/esm/loader:385:24) at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15) at async module.exports (/code/functions/fifteen.js:2:22) at async file:///opt/jello-app/patch/invokable.mjs:122:34